# Generated by Django 2.1.15 on 2020-10-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauraunt',
            name='logo',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
