# Generated by Django 2.1.15 on 2020-11-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201118_1730'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderarticle',
            unique_together={('quantity', 'article')},
        ),
    ]
