# Generated by Django 2.1.15 on 2020-11-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201119_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderarticle',
            unique_together=set(),
        ),
    ]
